### ISSUE TITLE
(1) Implement pagination in Rails

### ISSUE THREAD

**Issue by erskin19** [erskin19/tc359_rails_final#3]
On the index action of some model, you are displaying no more than 5 records per page (or another number that you think makes more sense), with clearly labeled to see the other pages of results

**Comment by erskin19** [comment]
@chrisvfritz Have I met the requirements for this skill?

**Comment by erskin19** [comment]
https://pure-mountain-5478.herokuapp.com/

**Comment by chrisvfritz** [comment]
:+1: Looks good!

**Comment by erskin19** [comment]
Awesome, does this mean I have a 4.0? @chrisvfritz

**Comment by chrisvfritz** [comment]
It... does! :tada: :balloon: :shipit:
